### PR TITLE
add id as a directive attribute returned on cropme:done to identify elem...

### PR DESCRIPTION
**Pull request by divyenduz**
Added id as a cropme directive element. So, multiple directives can be used using the id to identify them. Id is returned on cropme:done event. 

Please do give feedback on this, even if you would reject it.  

Thanks

### CODE REVIEW

**Comment by divyenduz** [comment]
Is their a existing functionality to achieve this ? I am using my own fork as bower but I would want to move to this repository. Let me know if there is a existing way or what can be do to get this feature merged.

Thanks

**Comment by PeterTrotter** [comment]
I'm about to fork this too. I think it would be better to use emit instead of broadcast for the done and loaded events (That's what I intend to implement).

That way you can capture it in the scope above and prevent it propagating without the need for a specific identifier for the child crop-me element.

**Comment by divyenduz** [comment]
I think ID is a better solution, as emit will force us to use $rootScope, some people hate using that as they don't understand it. ID on the other hand has less drawbacks, it can be used as a logical element identifier too.

What do you say ?

**Comment by PeterTrotter** [comment]
With $emit you just use scope.$emit(...) on your local scope. This event gets bubbled upwards and can be stopped. You don't need to catch it at the $rootScope you just catch it in a parent scope.

This means you can do
```html
<my-image-uploader>
  <crop-me ...></crop-me>
</my-image-uploader>
```
and catch it in the controller for myImageUploader.

I really dislike the idea that you would broadcast completion from the $rootScope as it's only benefit is that it doesn't require heirachy. But that does not seem to be the angular way as you should be dealing with the result of the image upload more locally and updating the model.

**Comment by PeterTrotter** [comment]
If this was a jQuery plugin I would be agreeing with using the id since that's quite a jQuery style thing to do.

**Comment by divyenduz** [comment]
@PeterTrotter :- Waiting for your fork then :+1:

**Comment by PeterTrotter** [comment]
I'm not convinced it's the right way but I'll be testing it on a project this week. Too much work not enough thinking...

**Comment by standup75** [comment]
I do think emit would make more sense than broadcast in this case. But the id would still make sense because 2 cropme directives could have the same parent scope. So I'm merging this

**Pull request merged**
